baseurl = "https://example.org/"  # please update this to your actual URL
languageCode = "en-us"
title = "tobeif-DTU"
theme = "PaperMod"




[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Research"
    name = "Research"
    url = "/Research"
    weight = 2

  [[menu.main]]
    identifier = "Courses"
    name = "Courses"
    url = "/"
    weight = 3

  [[menu.main]]
    identifier = "Supervision"
    name = "Supervision"
    url = "/"
    weight = 3






