baseurl = "https://example.org/"  # please update this to your actual URL
languageCode = "en-us"
title = "tobeif-DTU"
theme = "PaperMod"



[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Research"
    name = "Research"
    url = "/Research"
    weight = 2

  [[menu.main]]
    identifier = "Courses"
    name = "Courses"
    url = "/Courses"
    weight = 3

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/Projects"
    weight = 3




[params]
# env = "production"
# description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"

# author = "Tobias Eifler"
# ShowBreadCrumbs = true

# defaultTheme = "auto"
# ShowShareButtons = true
# ShowReadingTime = true
# displayFullLangName = true
# ShowPostNavLinks = true

  ShowCodeCopyButtons = true
# ShowRssButtonInSectionTermList = true
# ShowAllPagesInArchive = true
 ShowPageNums = true
# ShowToc = true
 images = [ "images/tobeif.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = ""
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  enabled = true  
  Title = "Tobias Eifler"
  Content = """
👋 Welcome to our small page that is summarising a bit of the stuff that we do in my small research group at DTU (Technical University of Denmark). I am Associate Professor in Engineering Design and Manufacturing Systems at the Department of Civil & Mechanical Engineering (DTU Construct) with an interest in all questions of product realisation, design uncertainty and variation consideration during product development and production. Accordingly my main research interests are methods, algorithms and other design tools that help exploring the design and configuration space. 

"""

# I specifically interested how product development and product realisation can benefit our lives, help us to navigate transformachieve  and assist us in better doing the things we care about.demo page of Hugo's theme PaperMod!



  [[params.socialIcons]]
  name = "github"
  title = "View Source on Github"
  url = "https://github.com/tobeif-DTU"

  [[params.socialIcons]]
  name = "Linkedin"
  title = "Join discord community"
  url = "https://www.linkedin.com/in/tobeif-DTU/"

  [[params.socialIcons]]
  name = "X"
  title = "Share PaperMod on X/Twitter"
  url = "https://www.nbcnews.com/tech/social-media/x-twitter-elon-musk-nazi-extremist-white-nationalist-accounts-rcna145020"

  [params.assets]
  disableHLJS = true


